# English translations of the Polish texts of the program (the source language is Polish).
# python tools/i18n_build.py checks this dictionary against the code and writes res/lang/en.po.
# None = the text is the same in both languages.
EN = {
    'Gracz 1': 'Player 1',
    'Gracz 2': 'Player 2',
    'stycznia': 'January',
    'lutego': 'February',
    'marca': 'March',
    'kwietnia': 'April',
    'maja': 'May',
    'czerwca': 'June',
    'lipca': 'July',
    'sierpnia': 'August',
    'września': 'September',
    'października': 'October',
    'listopada': 'November',
    'grudnia': 'December',
    'Komputer': 'Computer',
    'zagraj dobraną kartę albo odrzuć ją na śmietnik (kończy turę).': 'play the drawn card or discard it to the waste pile (ends the turn).',
    'zagraj karty lub dobierz z talii.': 'play cards or draw from the stock.',
    ' gra…': ' is playing…',
    'Zagraj dobraną kartę albo odrzuć ją na śmietnik (kończy turę).': 'Play the drawn card or discard it to the waste pile (ends the turn).',
    'Twój ruch: zagraj karty lub dobierz z talii.': 'Your move: play cards or draw from the stock.',
    ' wygrywa: pozbył się wszystkich kart!': ' wins: has got rid of all the cards!',
    ' wygrywa: po 400 turach ma mniej kart do zagrania.': ' wins: after 400 turns has fewer cards left to play.',
    'Wygrywasz! Pozbyłeś się wszystkich kart.': 'You win! You got rid of all your cards.',
    'Wygrywasz! Po 400 turach masz mniej kart do zagrania.': 'You win! After 400 turns you have fewer cards left to play.',
    ' pozbył się wszystkich kart. Przegrana.': ' got rid of all the cards. You lose.',
    'Po 400 turach ': 'After 400 turns ',
    ' ma mniej kart do zagrania. Przegrana.': ' has fewer cards left to play. You lose.',
    'Remis: nikt nie może już zagrać.': 'Draw: nobody can play any more.',
    'Takie same figury w magazynach: zaczynasz, bo Twój kolor jest starszy (pik, kier, karo, trefl).': 'Same ranks in the reserves: you start, because your suit is older (spades, hearts, diamonds, clubs).',
    'Takie same figury w magazynach: ': 'Same ranks in the reserves: ',
    ' zaczyna, bo jego kolor jest starszy (pik, kier, karo, trefl).': ' starts, because their suit is older (spades, hearts, diamonds, clubs).',
    'Identyczne karty w magazynach: rozstrzygnęły karty odkryte z talii. Zaczynasz.': 'Identical cards in the reserves: the cards turned over from the stock decided. You start.',
    'Identyczne karty w magazynach: rozstrzygnęły karty odkryte z talii. Zaczyna ': 'Identical cards in the reserves: the cards turned over from the stock decided. First to play: ',
    'Zaczynasz: masz starszą kartę w magazynie.': 'You start: you have the older card in the reserve.',
    ' zaczyna: ma starszą kartę w magazynie.': ' starts: has the older card in the reserve.',
    ' zaczyna (starsza karta w magazynie albo rozstrzygnięcie według zasad).': ' starts (the older card in the reserve, or decided by the rules).',
    'Wczytano ostatnią grę.': 'The last game has been loaded.',
    'Gra sieciowa': 'Network game',
    'Gra obu graczy rozeszła się (': "The two players' games have diverged (",
    '). Gra sieciowa została przerwana.': '). The network game has been stopped.',
    'Nie można nasłuchiwać: ': 'Cannot listen: ',
    'Wpisz adres IP hosta.': "Enter the host's IP address.",
    'Nie można rozpocząć łączenia.': 'Cannot start connecting.',
    'Czekam, aż ': 'Waiting for ',
    ' zgodzi się na nową partię…': ' to agree to a new game…',
    'Nick musi mieć co najmniej 3 znaki.': 'The nickname must have at least 3 characters.',
    'Wpisz adres serwera.': 'Enter the server address.',
    'Kod pokoju ma 4 znaki.': 'The room code has 4 characters.',
    'Połączono z ': 'Connected to ',
    '. Uzgadnianie…': '. Negotiating…',
    'Wynik zapisany. Twój bilans na serwerze: ': 'Result saved. Your record on the server: ',
    ' wygranych, ': ' wins, ',
    ' przegranych, ': ' losses, ',
    ' remisów.': ' draws.',
    ' opuścił grę.': ' has left the game.',
    'Ten nick zalogował się z innego miejsca.': 'This nickname has logged in from another place.',
    'Przeciwnik': 'Opponent',
    'Różne wersje gry: Ty masz ': 'Different game versions: you have ',
    ' ma ': ' has ',
    '.\nZaktualizujcie obie strony do tej samej wersji.': '.\nBoth of you must update to the same version.',
    '. Czekam na rozpoczęcie gry…': '. Waiting for the game to start…',
    ' proponuje nową partię. Zgadzasz się?': ' proposes a new game. Do you agree?',
    'Nowa partia': 'Rematch',
    ' nie chce nowej partii.': ' does not want a new game.',
    'Połączono z serwerem. Logowanie…': 'Connected to the server. Logging in…',
    'Połączono. Uzgadnianie…': 'Connected. Negotiating…',
    'Nie udało się połączyć z serwerem: ': 'Could not connect to the server: ',
    'Nie udało się połączyć: ': 'Could not connect: ',
    'Połączenie z przeciwnikiem zostało przerwane.': 'The connection to the opponent was lost.',
    'Połączenie z serwerem zostało zamknięte.': 'The connection to the server was closed.',
    'Połączenie zostało zamknięte.': 'The connection was closed.',
    'ruch przeciwnika nie w jego turze': "opponent's move out of turn",
    'błędny ruch': 'invalid move',
    'niedozwolony ruch przeciwnika': 'illegal move by the opponent',
    'niedozwolone dobranie': 'illegal draw',
    'niedozwolone odrzucenie': 'illegal discard',
    ' zapomniał dołożyć karty do fundamentu i traci turę.': ' forgot to play a card to the foundation and loses the turn.',
    'różne stany gry po turze': 'different game states after the turn',
    ' zapomniał dołożyć karty do fundamentu: traci turę!': ' forgot to play a card to the foundation: loses the turn!',
    'Zapomniałeś dołożyć karty do fundamentu: tracisz turę!': 'You forgot to play a card to the foundation: you lose the turn!',
    'Przymus: ta karta musi najpierw trafić na fundament.': 'Obligation: this card must go to the foundation first.',
    'Najpierw zagraj albo odrzuć dobraną kartę.': 'First play or discard the drawn card.',
    'Talia i śmietnik są puste. Kliknij talię (lub naciśnij D), żeby spasować.': 'The stock and the waste pile are empty. Click the stock (or press D) to pass.',
    'Podpowiedź: ta karta musi iść na fundament.': 'Hint: this card must go to the foundation.',
    'Podpowiedź: tak możesz zagrać.': 'Hint: you can play like this.',
    'Brak ruchów: odrzuć dobraną kartę na śmietnik.': 'No moves: discard the drawn card to the waste pile.',
    'Brak ruchów: dobierz kartę z talii.': 'No moves: draw a card from the stock.',
    'Brak ruchów: kliknij talię (lub naciśnij D), żeby spasować.': 'No moves: click the stock (or press D) to pass.',
    'Automatyczne ruchy są wyłączone (Ustawienia → Rozgrywka): przeciągnij kartę.': 'Automatic moves are off (Settings → Gameplay): drag the card.',
    'Ta karta nie ma żadnego dozwolonego ruchu.': 'This card has no legal move.',
    'Magazyn': 'Reserve',
    'Talia': 'Stock',
    'Dobrana': 'Drawn',
    'Śmietnik': 'Waste',
    'Nowa gra': 'New game',
    'Cofnij': 'Undo',
    'Podpowiedź': 'Hint',
    'Graj przez sieć ●': 'Play online ●',
    'Graj przez sieć': 'Play online',
    'Hot seat ●': None,
    'Hot seat': None,
    'Czat (': 'Chat (',
    'Czat': 'Chat',
    'Statystyki': 'Statistics',
    'Ustawienia': 'Settings',
    'Zasady': 'Rules',
    'Wersja ': 'Version ',
    '  ·  zbudowana ': '  ·  built ',
    'Zmiany działają od razu i są zapamiętywane w pliku .ini': 'Changes take effect at once and are saved in the .ini file',
    'Sprawdzaj aktualizacje przy starcie gry': 'Check for updates when the game starts',
    'Gra pyta w serwisie GitHub, czy jest nowsza wersja, i proponuje jej zainstalowanie.': 'The game asks GitHub whether a newer version exists and offers to install it.',
    ', zbudowana ': ', built ',
    'Obok programu leżą pliki: Garibaldi.ini (ustawienia i statystyki), Garibaldi.sav (zapis gry, tworzony na bieżąco) i garibaldka_ruchy.log (zapis wszystkich ruchów do analizy).': 'Next to the program are the files: Garibaldi.ini (settings and statistics), Garibaldi.sav (the saved game, kept up to date) and garibaldka_ruchy.log (a record of all moves, for analysis).',
    'Poziom gry (komputer)': 'Game level (computer)',
    'Poziom: ': 'Level: ',
    'Kliknij przycisk, żeby zmienić poziom. Poziomy różnią się tym, ile ruchów naprzód komputer przewiduje: Łatwy 1, Normalny 2, Trudny 4. Żaden nie pomija ruchów.': 'Click the button to change the level. The levels differ in how many moves ahead the computer looks: Easy 1, Normal 2, Hard 4. None of them overlooks moves.',
    'Automatyczne ruchy': 'Automatic moves',
    'Przymus fundamentu': 'Foundation obligation',
    'Karaj': 'Punish',
    'Przypomnij': 'Remind',
    'W grze z drugim graczem (hot seat, przez sieć) zawsze obowiązuje „Karaj”. Opcja „Przypomnij” działa tylko w grze z komputerem.': 'In a game with another player (hot seat, online) "Punish" always applies. The "Remind" option only works against the computer.',
    'Karaj: kto pominie ruch na fundament, natychmiast traci turę, a jego zagranie nie zostaje wykonane.': 'Punish: whoever misses a move to a foundation loses the turn at once, and their move is not carried out.',
    'Przypomnij: zamiast kary gra pokazuje obowiązkowy ruch na fundament i blokuje zagranie, które chciałeś wykonać. Dopóki go nie zrobisz, nie zagrasz niczego innego.': 'Remind: instead of a penalty the game shows the obligatory move to the foundation and blocks the move you wanted to make. Until you make it, you cannot play anything else.',
    'Dźwięk włączony': 'Sound on',
    'Głośność': 'Volume',
    'Własne dźwięki (WAV lub MP3)': 'Own sounds (WAV or MP3)',
    '(bez dźwięku)': '(no sound)',
    'domyślny': 'default',
    'Wybierz': 'Choose',
    'Kliknij pole skrótu i naciśnij klawisz. Każda akcja ma dwa skróty. Klawisz przypisany do jednej akcji jest zabierany innej.': 'Click a shortcut field and press a key. Every action has two shortcuts. A key assigned to one action is taken away from another.',
    'Naciśnij…': 'Press…',
    'Przywróć domyślne': 'Restore defaults',
    'Stałe: Ctrl+Z (cofnij), Enter (czat), Esc (zamknij okno).': 'Fixed: Ctrl+Z (undo), Enter (chat), Esc (close a window).',
    'Język zmieniony.': 'Language changed.',
    'Pliki dźwiękowe': 'Sound files',
    'Wszystkie pliki': 'All files',
    'Rozegrane i zakończone partie z tego komputera': 'Finished games on this computer',
    'Tryb gry': 'Game mode',
    'Rozegrane': 'Played',
    'Wygrane': 'Won',
    'Przegrane': 'Lost',
    'Remisy': 'Draws',
    '% wygranych': 'Win %',
    'Komputer: Łatwy': 'Computer: Easy',
    'Komputer: Normalny': 'Computer: Normal',
    'Komputer: Trudny': 'Computer: Hard',
    'Gra przez sieć': 'Online game',
    'Razem': 'Total',
    '% wygranych to wygrane podzielone przez rozegrane partie (remis liczy się jako rozegrana, a niewygrana). Partie z komputerem liczą się na poziomie, na którym je rozpoczęto, i tylko gdy zostały dokończone. Gry hot seat nie są liczone.': 'Win % is wins divided by games played (a draw counts as played, not won). Games against the computer count at the level they were started on, and only when finished. Hot seat games are not counted.',
    'Wyzeruj statystyki': 'Reset statistics',
    'Wyzerować wszystkie statystyki? Tego nie można cofnąć.': 'Reset all statistics? This cannot be undone.',
    'Twój nick': 'Your nickname',
    'Adres IP hosta (do połączenia)': "Host's IP address (to connect)",
    'Adres serwera': 'Server address',
    'Hasło serwera (od znajomych)': 'Server password (from friends)',
    'Kod pokoju (do dołączenia)': 'Room code (to join)',
    'Trwa gra z: ': 'Playing against: ',
    'Połączono': 'Connected',
    ' z ': ' to ',
    'Pokój otwarty. Podaj znajomemu ten kod i adres serwera. Czekam, aż dołączy…': 'Room open. Give your friend this code and the server address. Waiting for them to join…',
    'Czekam na znajomego (port ': 'Waiting for your friend (port ',
    ').\nPodaj mu jeden z adresów swojego komputera:\n': ").\nGive them one of your computer's addresses:\n",
    '      (nie udało się ustalić adresu)\n': '      (could not determine the address)\n',
    'Łączenie z serwerem…': 'Connecting to the server…',
    'Łączenie…': 'Connecting…',
    'Jeden z Was klika „Utwórz pokój” i podaje znajomemu kod, drugi wpisuje kod i klika „Dołącz”. Nick jest zastrzeżony na serwerze tylko dla Ciebie.': 'One of you clicks "Create room" and gives the other the code; the other enters the code and clicks "Join". The nickname is reserved on the server just for you.',
    'Jeden z Was klika „Hostuj grę”, drugi wpisuje adres IP hosta i klika „Połącz”.\nW sieci lokalnej adres hosta to np. 192.168.0.12.': 'One of you clicks "Host game"; the other enters the host\'s IP address and clicks "Connect".\nOn a local network the host\'s address is something like 192.168.0.12.',
    'Gra z drugim graczem': 'Game with another player',
    'Przez internet: serwer łączy Was kodem pokoju': 'Over the internet: the server connects you with a room code',
    'W sieci lokalnej: jeden gracz hostuje, drugi się łączy': 'On a local network: one player hosts, the other connects',
    'Sieć lokalna': 'Local network',
    'Utwórz pokój': 'Create room',
    'Hostuj grę': 'Host game',
    'Dołącz': 'Join',
    'Połącz': 'Connect',
    'Opuść grę': 'Leave game',
    'Rozłącz': 'Disconnect',
    'Kod pokoju': 'Room code',
    'Czat z ': 'Chat with ',
    'Napisz wiadomość i naciśnij Enter': 'Type a message and press Enter',
    'Bilans z ': 'Record vs ',
    '  (remisy: ': '  (draws: ',
    'Remis': 'Draw',
    ' wygrywa': ' wins',
    'Wygrywasz!': 'You win!',
    'Komputer wygrał': 'The computer wins',
    'Kliknij „Nowa gra” (F2), aby zagrać ponownie': 'Click "New game" (F2) to play again',
    'Zakończyć grę dwóch graczy i zacząć nową grę z komputerem?\nBieżąca partia zostanie porzucona.': 'End the two-player game and start a new game against the computer?\nThe current game will be abandoned.',
    'Zacząć nową grę w trybie hot seat (dwóch graczy przy jednym komputerze)?\nBieżąca partia zostanie porzucona.': 'Start a new hot seat game (two players at one computer)?\nThe current game will be abandoned.',
    'Przenoszę sekwens kolejnymi ruchami…': 'Moving the sequence in several moves…',
    'Przenoszę kartę…': 'Moving the card…',
    'Ten sekwens nie ma gdzie przejść (albo brakuje wolnego miejsca).': 'This sequence has nowhere to go (or there is not enough free space).',
    'Za mało wolnego miejsca, żeby przenieść ten sekwens.': 'Not enough free space to move this sequence.',
    'To nie jest sekwens: przenosić można tylko ułożone karty (malejąco, na przemian kolory).': 'This is not a sequence: only cards laid out in order (descending, alternating colours) can be moved.',
    'Dostępna nowsza wersja gry: ': 'A newer version of the game is available: ',
    ' (masz ': ' (you have ',
    ').\n\nZaktualizować teraz?': ').\n\nUpdate now?',
    '\n\nCo nowego:\n': "\n\nWhat's new:\n",
    'Aktualizacja dostępna': 'Update available',
    'Nie udało się pobrać aktualizacji. Spróbuj ponownie później.': 'Could not download the update. Try again later.',
    'Aktualizacja': 'Update',
    'Pobrano aktualizację, ale nie udało się jej zainstalować automatycznie.': 'The update was downloaded, but it could not be installed automatically.',
    'Błąd inicjalizacji Direct2D.': 'Direct2D initialisation error.',
    'Nie można utworzyć okna.': 'Cannot create the window.',
    'Łatwy': 'Easy',
    'Normalny': 'Normal',
    'Trudny': 'Hard',
    'Ogólne': 'General',
    'Rozgrywka': 'Gameplay',
    'Grafika': 'Graphics',
    'Dźwięk': 'Sound',
    'Sterowanie': 'Controls',
    'Cel gry': 'Goal',
    'Rozkład kart': 'The layout',
    'Każdy gracz ma własną talię 52 kart (Ty niebieską, komputer czerwoną).': 'Each player has their own deck of 52 cards (you the blue one, the computer the red one).',
    '12 kart zakrytych i 1 odkryta na wierzchu.': '12 cards face down and 1 face up on top.',
    '35 kart. Dobierasz je po jednej.': '35 cards. You draw them one at a time.',
    'Dobrana karta': 'Drawn card',
    'karta odkryta z talii. Musisz ją zagrać albo odrzucić.': 'a card turned over from the stock. You must play it or discard it.',
    'odrzucone karty. Gdy talia się skończy, śmietnik staje się nową talią.': 'discarded cards. When the stock runs out, the waste pile becomes the new stock.',
    'Kolumny': 'Columns',
    '8 wspólnych kolumn (na początku po 4 karty od każdego gracza).': '8 shared columns (at the start 4 cards from each player).',
    'Fundamenty': 'Foundations',
    '8 stosów budowanych od asa do króla w jednym kolorze. Mają zarezerwowane kolory, po dwa na kolor, w kolejności starszeństwa: pik, kier, karo, trefl. As zaczyna fundament swojego koloru.': '8 piles built from ace to king in one suit. They have reserved suits, two per suit, in order of seniority: spades, hearts, diamonds, clubs. An ace starts the foundation of its suit.',
    'Dozwolone zagrania': 'Allowed moves',
    'Na fundament': 'To a foundation',
    'as, a potem kolejne karty tego samego koloru.': 'an ace, then the following cards of the same suit.',
    'Na kolumnę': 'To a column',
    'karta o jeden niższa, w innym kolorze (np. 6♥ na 7♣). Pusta kolumna przyjmie dowolną kartę.': 'a card one lower, of the other colour (e.g. 6♥ on 7♣). An empty column accepts any card.',
    'Cały sekwens': 'A whole sequence',
    'karty przekłada się po jednej, ale gdy da się przenieść ułożony ciąg kolejnymi ruchami (wolne kolumny lub miejsca na innych kolumnach), możesz złapać jego pierwszą kartę. Gra sama wykona i pokaże wszystkie ruchy.': 'cards are moved one at a time, but when an ordered run can be moved by consecutive moves (free columns or places on other columns), you can pick up its first card. The game makes and shows all the moves itself.',
    'Na magazyn lub śmietnik przeciwnika': "To the opponent's reserve or waste pile",
    'karta tego samego koloru o jeden wyższa lub niższa. Taka karta zasłania przeciwnikowi jego kartę.': "a card of the same suit one higher or lower. Such a card covers the opponent's card.",
    'Ścisły przymus': 'Strict obligation',
    'Każdą kartę, którą możesz zagrać na fundament (wierzch magazynu, dobrana karta, wierzch śmietnika lub kolumny), musisz tam dołożyć.': 'Every card you can play to a foundation (top of the reserve, the drawn card, top of the waste pile or of a column) you must put there.',
    'Dopóki jakaś karta może iść na fundament, wolno zagrywać tylko na fundamenty. Kto zapomni i zagra inaczej (na kolumnę, na stos przeciwnika), dobierze kartę, odrzuci ją lub spasuje, traci turę. Takie zagranie nie zostaje wykonane.': "As long as some card can go to a foundation, you may only play to foundations. Whoever forgets and plays otherwise (to a column, to the opponent's pile), draws a card, discards it or passes, loses the turn. Such a move is not carried out.",
    'W Ustawieniach (Rozgrywka) możesz zamiast „Karaj” wybrać „Przypomnij”: wtedy nie ma kary, tylko gra pokazuje obowiązkowy ruch na fundament i blokuje zagranie, które chciałeś wykonać. Dotyczy tylko gry z komputerem: w hot seat i przez sieć zawsze obowiązuje „Karaj”.': 'In Settings (Gameplay) you can choose "Remind" instead of "Punish": then there is no penalty, the game just shows the obligatory move to the foundation and blocks the move you wanted to make. This only applies to games against the computer: in hot seat and online games "Punish" always applies.',
    'Przebieg tury': 'The turn',
    '1.': None,
    'Graj kartami z magazynu, śmietnika i kolumn, ile chcesz.': 'Play cards from the reserve, the waste pile and the columns as many as you like.',
    '2.': None,
    'Gdy nie możesz lub nie chcesz grać dalej, dobierz kartę z talii.': 'When you cannot or do not want to play on, draw a card from the stock.',
    '3.': None,
    'Zagraj ją albo odrzuć na swój śmietnik. Odrzucenie kończy turę.': 'Play it or discard it onto your waste pile. Discarding ends the turn.',
    'Pas': 'Pass',
    'możliwy tylko wtedy, gdy talia i śmietnik są puste.': 'possible only when the stock and the waste pile are empty.',
    'Płomień': 'The flame',
    'płonie obok magazynu gracza, którego jest tura.': 'burns next to the reserve of the player whose turn it is.',
    'Kto zaczyna': 'Who starts',
    'Zaczyna ten, kto ma starszą kartę w magazynie (as jest najmłodszy, król najstarszy).': 'The one with the older card in the reserve starts (the ace is the youngest, the king the oldest).',
    'Takie same figury: decyduje kolor (pik, kier, karo, trefl). Identyczne karty: każdy odkrywa pierwszą kartę z talii i ta rozstrzyga tak samo; jeśli znów są identyczne, odkrywane są kolejne. Odkryte karty wracają pod talie.': 'Same ranks: the suit decides (spades, hearts, diamonds, clubs). Identical cards: each player turns over the first card of the stock and it decides in the same way; if they are identical again, the next ones are turned over. The turned cards go back under the stocks.',
    'Sterowanie myszą': 'Mouse controls',
    'Kliknięcie karty': 'Clicking a card',
    'przenosi ją na najlepsze miejsce (opcja „Automatyczne ruchy” w Ustawieniach). Dobrana karta trafia na śmietnik tylko wtedy, gdy nie ma dla niej żadnego innego ruchu.': 'moves it to the best place (the "Automatic moves" option in Settings). The drawn card goes to the waste pile only when it has no other move.',
    'Kliknięcie własnej talii': 'Clicking your own stock',
    'dobiera kartę; gdy nie ma czego dobrać, spasowuje.': 'draws a card; when there is nothing to draw, passes.',
    'Przeciąganie': 'Dragging',
    'przenosi kartę lub cały sekwens tam, gdzie chcesz. Zielone ramki pokazują dozwolone miejsca.': 'moves a card or a whole sequence where you want. Green frames show the allowed places.',
    'Skróty klawiszowe': 'Keyboard shortcuts',
    'Spacja': 'Space',
    'dobierz kartę': 'draw a card',
    'D': None,
    'odrzuć dobraną kartę / pas': 'discard the drawn card / pass',
    'H': None,
    'podpowiedź (karta sama pokazuje ruch)': 'hint (the card shows the move itself)',
    'Backspace, U, Ctrl+Z': None,
    'cofnij': 'undo',
    'F2': None,
    'nowa gra': 'new game',
    'F1 / F3 / F4': None,
    'zasady / ustawienia / statystyki': 'rules / settings / statistics',
    'F5 / F7': None,
    'graj przez sieć / hot seat': 'play online / hot seat',
    'M': None,
    'dźwięk włączony / wyłączony': 'sound on / off',
    'Podane są skróty domyślne. Wszystkie (poza Ctrl+Z) możesz zmienić w Ustawieniach → Sterowanie.': 'These are the default shortcuts. All of them (except Ctrl+Z) can be changed in Settings → Controls.',
    'Przycisk „Graj przez sieć”: jeden gracz klika „Hostuj grę” i podaje znajomemu adres IP swojego komputera, drugi wpisuje go i klika „Połącz”. W zakładce „Internet” jeden gracz klika „Utwórz pokój” i podaje kod, drugi wpisuje kod i klika „Dołącz”. Obie kopie gry muszą mieć tę samą wersję. W grze sieciowej nie ma cofania ani podpowiedzi.': 'The "Play online" button: one player clicks "Host game" and gives a friend the IP address of their computer; the other enters it and clicks "Connect". In the "Internet" tab one player clicks "Create room" and gives a code, the other enters the code and clicks "Join". Both copies of the game must be the same version. In a network game there is no undo and no hints.',
    'przycisk „Czat” (widoczny tylko w grze sieciowej) lub Enter; pod polem wiadomości są emotki.': 'the "Chat" button (visible only in a network game) or Enter; below the message field are emotes.',
    'przycisk „Nowa gra” proponuje ją przeciwnikowi, który musi się zgodzić.': 'the "New game" button proposes it to the opponent, who must agree.',
    'Przycisk „Hot seat” zaczyna grę dwóch osób przy jednym komputerze. Gracz 1 siedzi na dole, Gracz 2 na górze; zagrywa ten, czyja jest tura (płomień obok magazynu). Obaj widzą wszystkie karty, które leżą na stole. Cofać można tylko ruchy z własnej tury, a podpowiedź działa dla gracza, którego jest ruch. Takie partie nie wchodzą do statystyk. Ponowne kliknięcie przycisku wraca do gry z komputerem.': 'The "Hot seat" button starts a game of two people at one computer. Player 1 sits at the bottom, Player 2 at the top; whoever\'s turn it is plays (the flame next to the reserve). Both see all the cards lying on the table. You can only undo moves from your own turn, and the hint works for the player whose move it is. Such games do not count in the statistics. Clicking the button again returns to a game against the computer.',
    'Statystyki i ustawienia': 'Statistics and settings',
    'liczba rozegranych i wygranych partii oraz procent wygranych osobno dla każdego poziomu komputera i dla gry przez sieć.': 'the number of games played and won and the win percentage, separately for each computer level and for network games.',
    'aktualizacje, poziom gry, automatyczne ruchy, przymus fundamentu, głośność i własne dźwięki, skróty klawiszowe. Gra pamięta ostatnio wybraną grupę.': 'updates, game level, automatic moves, foundation obligation, volume and own sounds, keyboard shortcuts. The game remembers the group you selected last.',
    'Cofanie i zapis gry': 'Undo and saving',
    'Cofnij cofa Twoją ostatnią czynność: ruch, dobranie, odrzucenie, a przeniesienie całego sekwensu jako jeden krok. Jeśli ta czynność skończyła turę, cofa też ruchy komputera wykonane od tamtej pory.': "Undo takes back your last action: a move, a draw, a discard, and moving a whole sequence as one step. If that action ended the turn, it also takes back the computer's moves made since then.",
    'Stan gry zapisuje się na bieżąco i wczytuje przy następnym uruchomieniu (również po awarii).': 'The state of the game is saved continuously and loaded at the next start (also after a crash).',
    'Komputer ma trzy poziomy trudności: Łatwy, Normalny i Trudny (zmieniasz je w Ustawieniach). Różnią się wyłącznie tym, ile ruchów naprzód przewidują: 1, 2 i 4. Komputer zawsze zagrywa to, co uzna za najlepszą serię ruchów, i nie kończy tury, gdy jest wolna kolumna, w którą da się coś położyć. Gra według zasad opisanych w pliku AI_RULES.md.': 'The computer has three difficulty levels: Easy, Normal and Hard (change them in Settings). They differ only in how many moves ahead they look: 1, 2 and 4. The computer always plays what it judges the best series of moves, and does not end its turn when there is a free column that can take a card. It plays by the rules described in the file AI_RULES.md.',
    'Dobierz kartę z talii': 'Draw a card from the stock',
    'Odrzuć kartę / pas': 'Discard a card / pass',
    'Dźwięk włączony / wyłączony': 'Sound on / off',
    'Ruch karty': 'Card move',
    'Wygrana': 'Win',
    'Przegrana lub remis': 'Loss or draw',
    'Ruch niemożliwy': 'Impossible move',
    'Cofnięcie ruchu': 'Undo of a move',
    'Przesunięcie płomienia': 'Flame moving',
    'Błąd serwera.': 'Server error.',
    'Nieprawidłowe hasło serwera.': 'Wrong server password.',
    'Nick: 3-16 znaków, litery, cyfry, _ lub -.': 'Nickname: 3-16 characters, letters, digits, _ or -.',
    'Błędny klucz gracza.': 'Invalid player key.',
    'Serwer nie przyjmuje już nowych nicków.': 'The server accepts no more new nicknames.',
    'Ten nick jest już zajęty przez innego gracza.': 'This nickname is already taken by another player.',
    'Najpierw zaloguj się.': 'Log in first.',
    'Brak wolnych pokoi, spróbuj za chwilę.': 'No free rooms, try again in a moment.',
    'Nie ma takiego pokoju.': 'There is no such room.',
    'Pokój jest już pełny.': 'The room is already full.',
    'Kliknięcie przenosi kartę tylko na fundament (Ustawienia → Rozgrywka): przeciągnij kartę.': 'Clicking only moves a card to a foundation (Settings → Gameplay): drag the card.',
    'Zawsze': 'Always',
    'Tylko na fundament': 'Only to a foundation',
    'Nigdy': 'Never',
    'Kliknięcie karty przenosi ją na najlepsze miejsce (kliknięcie karty w kolumnie przenosi cały sekwens). Inne ruchy możesz też wykonywać przeciągając.': 'Clicking a card moves it to the best place (clicking a card in a column moves the whole sequence). You can also make other moves by dragging.',
    'Kliknięcie karty przenosi ją tylko na fundament. Pozostałe ruchy wykonujesz przeciągając; kliknięcie własnej talii nadal dobiera kartę.': 'Clicking a card moves it only to a foundation. You make other moves by dragging; clicking your own stock still draws a card.',
    'Karty przenosi się tylko przeciąganiem; kliknięcie własnej talii nadal dobiera kartę.': 'Cards are moved by dragging only; clicking your own stock still draws a card.',
    'Prędkość animacji kart': 'Card animation speed',
    'Dotyczy wyłącznie animacji kart (przesuwanie, odwracanie, rozdawanie). Domyślnie 100%.': 'Applies only to the animation of the cards (moving, turning over, dealing). Default 100%.',
    'Jako pierwszy pozbądź się wszystkich swoich kart: z magazynu, z talii i ze śmietnika.': 'Be the first to get rid of all your cards: from the reserve, from the stock and from the waste pile.',
    'Pominięty ruch na fundament': 'Missed foundation move',
    'Odsłonięta karta musi najpierw trafić na fundament: przenoszenie sekwensu przerwane.': 'The uncovered card must go to a foundation first: moving the sequence was interrupted.',
}
