# English translations, in the order in which tools/i18n_extract.py lists the Polish texts of the program.
# (polish beginning, english). The beginning is only a check that the pairs are in step. None = the same in both languages.
EN = [
("Gracz 1", "Player 1"), ("Gracz 2", "Player 2"),
("stycznia", "January"), ("lutego", "February"), ("marca", "March"), ("kwietnia", "April"), ("maja", "May"), ("czerwca", "June"),
("lipca", "July"), ("sierpnia", "August"), ("września", "September"), ("października", "October"), ("listopada", "November"), ("grudnia", "December"),
("Komputer", "Computer"),
("zagraj dobraną", "play the drawn card or discard it to the waste pile (ends the turn)."),
("zagraj karty l", "play cards or draw from the stock."),
(" gra…", " is playing…"),
("Zagraj dobraną", "Play the drawn card or discard it to the waste pile (ends the turn)."),
("Twój ruch: zag", "Your move: play cards or draw from the stock."),
(" wygrywa: pozb", " wins: has got rid of all the cards!"),
(" wygrywa: po 4", " wins: after 400 turns has fewer cards left to play."),
("Wygrywasz! Poz", "You win! You got rid of all your cards."),
("Wygrywasz! Po ", "You win! After 400 turns you have fewer cards left to play."),
(" pozbył się", " got rid of all the cards. You lose."),
("Po 400 turach", "After 400 turns "),
(" ma mniej kart", " has fewer cards left to play. You lose."),
("Remis: nikt", "Draw: nobody can play any more."),
("Takie same fig", "Same ranks in the reserves: you start, because your suit is older (spades, hearts, diamonds, clubs)."),
("Takie same fig", "Same ranks in the reserves: "),
(" zaczyna, bo j", " starts, because their suit is older (spades, hearts, diamonds, clubs)."),
("Identyczne kar", "Identical cards in the reserves: the cards turned over from the stock decided. You start."),
("Identyczne kar", "Identical cards in the reserves: the cards turned over from the stock decided. First to play: "),
("Zaczynasz: ma", "You start: you have the older card in the reserve."),
(" zaczyna: ma s", " starts: has the older card in the reserve."),
(" zaczyna (star", " starts (the older card in the reserve, or decided by the rules)."),
("Wczytano ostat", "The last game has been loaded."),
("Gra sieciowa", "Network game"),
("Gra obu graczy", "The two players' games have diverged ("),
("). Gra sieciow", "). The network game has been stopped."),
("Nie można nasł", "Cannot listen: "),
("Wpisz adres IP", "Enter the host's IP address."),
("Nie można rozp", "Cannot start connecting."),
("Czekam, aż ", "Waiting for "),
(" zgodzi się na", " to agree to a new game…"),
("Nick musi mieć", "The nickname must have at least 3 characters."),
("Wpisz adres se", "Enter the server address."),
("Kod pokoju ma ", "The room code has 4 characters."),
("Połączono z ", "Connected to "),
(". Uzgadnianie…", ". Negotiating…"),
("Wynik zapisan", "Result saved. Your record on the server: "),
(" wygranych, ", " wins, "), (" przegranych, ", " losses, "), (" remisów.", " draws."),
(" opuścił grę.", " has left the game."),
("Ten nick zalog", "This nickname has logged in from another place."),
("Przeciwnik", "Opponent"),
("Różne wersje ", "Different game versions: you have "),
(" ma ", " has "),
(".\nZaktualizuj", ".\nBoth of you must update to the same version."),
(". Czekam na ro", ". Waiting for the game to start…"),
(" proponuje now", " proposes a new game. Do you agree?"),
("Nowa partia", "Rematch"),
(" nie chce nowe", " does not want a new game."),
("Połączono z se", "Connected to the server. Logging in…"),
("Połączono. Uzg", "Connected. Negotiating…"),
("Nie udało się ", "Could not connect to the server: "),
("Nie udało się ", "Could not connect: "),
("Połączenie z p", "The connection to the opponent was lost."),
("Połączenie z s", "The connection to the server was closed."),
("Połączenie zos", "The connection was closed."),
("ruch przeciwn", "opponent's move out of turn"),
("błędny ruch", "invalid move"),
("niedozwolony ", "illegal move by the opponent"),
("niedozwolone ", "illegal draw"),
("niedozwolone ", "illegal discard"),
(" zapomniał do", " forgot to play a card to the foundation and loses the turn."),
("różne stany g", "different game states after the turn"),
(" zapomniał do", " forgot to play a card to the foundation: loses the turn!"),
("Zapomniałeś d", "You forgot to play a card to the foundation: you lose the turn!"),
("Przymus: ta k", "Obligation: this card must go to the foundation first."),
("Najpierw zagr", "First play or discard the drawn card."),
("Talia i śmiet", "The stock and the waste pile are empty. Click the stock (or press D) to pass."),
("Podpowiedź: t", "Hint: this card must go to the foundation."),
("Podpowiedź: t", "Hint: you can play like this."),
("Brak ruchów: ", "No moves: discard the drawn card to the waste pile."),
("Brak ruchów: ", "No moves: draw a card from the stock."),
("Brak ruchów: ", "No moves: click the stock (or press D) to pass."),
("Automatyczne ", "Automatic moves are off (Settings → Gameplay): drag the card."),
("Ta karta nie ", "This card has no legal move."),
("Magazyn", "Reserve"), ("Talia", "Stock"), ("Dobrana", "Drawn"), ("Śmietnik", "Waste"),
("Nowa gra", "New game"), ("Cofnij", "Undo"), ("Podpowiedź", "Hint"),
("Graj przez si", "Play online ●"), ("Graj przez si", "Play online"),
("Hot seat ●", None), ("Hot seat", None),
("Czat (", "Chat ("), ("Czat", "Chat"), ("Statystyki", "Statistics"), ("Ustawienia", "Settings"), ("Zasady", "Rules"),
("Wersja ", "Version "), ("  ·  zbudowana", "  ·  built "),
("Zmiany działa", "Changes take effect at once and are saved in the .ini file"),
("Sprawdzaj akt", "Check for updates when the game starts"),
("Gra pyta w se", "The game asks GitHub whether a newer version exists and offers to install it."),
("Język", "Language"),
(", zbudowana ", ", built "),
("Obok programu", "Next to the program are the files: Garibaldi.ini (settings and statistics), Garibaldi.sav (the saved game, kept up to date) and garibaldka_ruchy.log (a record of all moves, for analysis)."),
("Poziom gry (k", "Game level (computer)"),
("Poziom: ", "Level: "),
("Kliknij przyc", "Click the button to change the level. The levels differ in how many moves ahead the computer looks: Easy 1, Normal 2, Hard 4. None of them overlooks moves."),
("Automatyczne ", "Automatic moves"),
("Kliknięcie ka", "Clicking a card moves it to the best place (clicking a card in a column moves the whole sequence). When off, cards can only be moved by dragging; clicking your own stock still draws a card."),
("Przymus funda", "Foundation obligation"),
("Karaj", "Punish"), ("Przypomnij", "Remind"),
("W grze z drug", "In a game with another player (hot seat, online) \"Punish\" always applies. The \"Remind\" option only works against the computer."),
("Karaj: kto po", "Punish: whoever misses a move to a foundation loses the turn at once, and their move is not carried out."),
("Przypomnij: z", "Remind: instead of a penalty the game shows the obligatory move to the foundation and blocks the move you wanted to make. Until you make it, you cannot play anything else."),
("Na razie brak", "No graphics settings yet."),
("Dźwięk włącz", "Sound on"),
("Głośność", "Volume"),
("Własne dźwięk", "Own sounds (WAV or MP3)"),
("(bez dźwięku", "(no sound)"),
("domyślny", "default"),
("Wybierz", "Choose"),
("Kliknij pole ", "Click a shortcut field and press a key. Every action has two shortcuts. A key assigned to one action is taken away from another."),
("Naciśnij…", "Press…"),
("Przywróć domy", "Restore defaults"),
("Stałe: Ctrl+Z", "Fixed: Ctrl+Z (undo), Enter (chat), Esc (close a window)."),
("Język zmienio", "Language changed."),
("Pliki dźwięko", "Sound files"),
("Wszystkie pli", "All files"),
("Rozegrane i z", "Finished games on this computer"),
("Tryb gry", "Game mode"),
("Rozegrane", "Played"), ("Wygrane", "Won"), ("Przegrane", "Lost"), ("Remisy", "Draws"), ("% wygranych", "Win %"),
("Komputer: Łat", "Computer: Easy"), ("Komputer: Nor", "Computer: Normal"), ("Komputer: Tru", "Computer: Hard"),
("Gra przez sie", "Online game"), ("Razem", "Total"),
("% wygranych t", "Win % is wins divided by games played (a draw counts as played, not won). Games against the computer count at the level they were started on, and only when finished. Hot seat games are not counted."),
("Wyzeruj staty", "Reset statistics"),
("Wyzerować wsz", "Reset all statistics? This cannot be undone."),
("Twój nick", "Your nickname"),
("Adres IP host", "Host's IP address (to connect)"),
("Adres serwera", "Server address"),
("Hasło serwera", "Server password (from friends)"),
("Kod pokoju (d", "Room code (to join)"),
("Trwa gra z: ", "Playing against: "),
("Połączono", "Connected"),
(" z ", " to "),
("Pokój otwart", "Room open. Give your friend this code and the server address. Waiting for them to join…"),
("Czekam na zna", "Waiting for your friend (port "),
(").\nPodaj mu j", ").\nGive them one of your computer's addresses:\n"),
("      (nie uda", "      (could not determine the address)\n"),
("Łączenie z se", "Connecting to the server…"),
("Łączenie…", "Connecting…"),
("Jeden z Was k", "One of you clicks \"Create room\" and gives the other the code; the other enters the code and clicks \"Join\". The nickname is reserved on the server just for you."),
("Jeden z Was k", "One of you clicks \"Host game\"; the other enters the host's IP address and clicks \"Connect\".\nOn a local network the host's address is something like 192.168.0.12."),
("Gra z drugim ", "Game with another player"),
("Przez interne", "Over the internet: the server connects you with a room code"),
("W sieci lokal", "On a local network: one player hosts, the other connects"),
("Sieć lokalna", "Local network"),
("Utwórz pokój", "Create room"), ("Hostuj grę", "Host game"), ("Dołącz", "Join"), ("Połącz", "Connect"),
("Opuść grę", "Leave game"), ("Rozłącz", "Disconnect"), ("Kod pokoju", "Room code"),
("Czat z ", "Chat with "),
("Napisz wiadom", "Type a message and press Enter"),
("Bilans z ", "Record vs "),
("  (remisy: ", "  (draws: "),
("Remis", "Draw"),
(" wygrywa", " wins"),
("Wygrywasz!", "You win!"),
("Komputer wygr", "The computer wins"),
("Kliknij „Nowa", "Click \"New game\" (F2) to play again"),
("Zakończyć grę", "End the two-player game and start a new game against the computer?\nThe current game will be abandoned."),
("Zacząć nową g", "Start a new hot seat game (two players at one computer)?\nThe current game will be abandoned."),
("Przenoszę sek", "Moving the sequence in several moves…"),
("Przenoszę kar", "Moving the card…"),
("Ten sekwens n", "This sequence has nowhere to go (or there is not enough free space)."),
("Za mało wolne", "Not enough free space to move this sequence."),
("To nie jest s", "This is not a sequence: only cards laid out in order (descending, alternating colours) can be moved."),
("Dostępna nows", "A newer version of the game is available: "),
(" (masz ", " (you have "),
(").\n\nZaktual", ").\n\nUpdate now?"),
("\n\nCo nowego:", "\n\nWhat's new:\n"),
("Aktualizacja ", "Update available"),
("Nie udało się", "Could not download the update. Try again later."),
("Aktualizacja", "Update"),
("Pobrano aktua", "The update was downloaded, but it could not be installed automatically."),
("Błąd inicjali", "Direct2D initialisation error."),
("Nie można utw", "Cannot create the window."),
("Łatwy", "Easy"), ("Normalny", "Normal"), ("Trudny", "Hard"),
("Ogólne", "General"), ("Rozgrywka", "Gameplay"), ("Grafika", "Graphics"), ("Dźwięk", "Sound"), ("Sterowanie", "Controls"),
("Cel gry", "Goal"),
("Jako pierwszy", "Be the first to get rid of all your cards: from the reserve, from the stock and from the waste pile. Emptying the reserve alone is not enough."),
("Rozkład kart", "The layout"),
("Każdy gracz m", "Each player has their own deck of 52 cards (you the blue one, the computer the red one)."),
("12 kart zakry", "12 cards face down and 1 face up on top."),
("35 kart. Dobi", "35 cards. You draw them one at a time."),
("Dobrana karta", "Drawn card"),
("karta odkryta", "a card turned over from the stock. You must play it or discard it."),
("odrzucone kar", "discarded cards. When the stock runs out, the waste pile becomes the new stock."),
("Kolumny", "Columns"),
("8 wspólnych k", "8 shared columns (at the start 4 cards from each player)."),
("Fundamenty", "Foundations"),
("8 stosów budo", "8 piles built from ace to king in one suit. They have reserved suits, two per suit, in order of seniority: spades, hearts, diamonds, clubs. An ace starts the foundation of its suit."),
("Dozwolone zag", "Allowed moves"),
("Na fundament", "To a foundation"),
("as, a potem k", "an ace, then the following cards of the same suit."),
("Na kolumnę", "To a column"),
("karta o jeden", "a card one lower, of the other colour (e.g. 6♥ on 7♣). An empty column accepts any card."),
("Cały sekwens", "A whole sequence"),
("karty przekład", "cards are moved one at a time, but when an ordered run can be moved by consecutive moves (free columns or places on other columns), you can pick up its first card. The game makes and shows all the moves itself."),
("Na magazyn lu", "To the opponent's reserve or waste pile"),
("karta tego sa", "a card of the same suit one higher or lower. Such a card covers the opponent's card."),
("Ścisły przymu", "Strict obligation"),
("Każdą kartę, ", "Every card you can play to a foundation (top of the reserve, the drawn card, top of the waste pile or of a column) you must put there."),
("Dopóki jakaś ", "As long as some card can go to a foundation, you may only play to foundations. Whoever forgets and plays otherwise (to a column, to the opponent's pile), draws a card, discards it or passes, loses the turn. Such a move is not carried out."),
("W Ustawieniac", "In Settings (Gameplay) you can choose \"Remind\" instead of \"Punish\": then there is no penalty, the game just shows the obligatory move to the foundation and blocks the move you wanted to make. This only applies to games against the computer: in hot seat and online games \"Punish\" always applies."),
("Przebieg tury", "The turn"),
("1.", None),
("Graj kartami ", "Play cards from the reserve, the waste pile and the columns as many as you like."),
("2.", None),
("Gdy nie możes", "When you cannot or do not want to play on, draw a card from the stock."),
("3.", None),
("Zagraj ją alb", "Play it or discard it onto your waste pile. Discarding ends the turn."),
("Pas", "Pass"),
("możliwy tylko", "possible only when the stock and the waste pile are empty."),
("Płomień", "The flame"),
("płonie obok m", "burns next to the reserve of the player whose turn it is."),
("Kto zaczyna", "Who starts"),
("Zaczyna ten, ", "The one with the older card in the reserve starts (the ace is the youngest, the king the oldest)."),
("Takie same fi", "Same ranks: the suit decides (spades, hearts, diamonds, clubs). Identical cards: each player turns over the first card of the stock and it decides in the same way; if they are identical again, the next ones are turned over. The turned cards go back under the stocks."),
("Sterowanie my", "Mouse controls"),
("Kliknięcie ka", "Clicking a card"),
("przenosi ją n", "moves it to the best place (the \"Automatic moves\" option in Settings). The drawn card goes to the waste pile only when it has no other move."),
("Kliknięcie wł", "Clicking your own stock"),
("dobiera kartę", "draws a card; when there is nothing to draw, passes."),
("Przeciąganie", "Dragging"),
("przenosi kart", "moves a card or a whole sequence where you want. Green frames show the allowed places."),
("Skróty klawis", "Keyboard shortcuts"),
("Spacja", "Space"),
("dobierz kartę", "draw a card"),
("D", None),
("odrzuć dobran", "discard the drawn card / pass"),
("H", None),
("podpowiedź (k", "hint (the card shows the move itself)"),
("Backspace, U,", None),
("cofnij", "undo"),
("F2", None),
("nowa gra", "new game"),
("F1 / F3 / F4", None),
("zasady / usta", "rules / settings / statistics"),
("F5 / F7", None),
("graj przez si", "play online / hot seat"),
("M", None),
("dźwięk włącz", "sound on / off"),
("Podane są skr", "These are the default shortcuts. All of them (except Ctrl+Z) can be changed in Settings → Controls."),
("Przycisk „Gra", "The \"Play online\" button: one player clicks \"Host game\" and gives a friend the IP address of their computer; the other enters it and clicks \"Connect\". In the \"Internet\" tab one player clicks \"Create room\" and gives a code, the other enters the code and clicks \"Join\". Both copies of the game must be the same version. In a network game there is no undo and no hints."),
("przycisk „Cza", "the \"Chat\" button (visible only in a network game) or Enter; below the message field are emotes."),
("przycisk „Now", "the \"New game\" button proposes it to the opponent, who must agree."),
("Przycisk „Hot", "The \"Hot seat\" button starts a game of two people at one computer. Player 1 sits at the bottom, Player 2 at the top; whoever's turn it is plays (the flame next to the reserve). Both see all the cards lying on the table. You can only undo moves from your own turn, and the hint works for the player whose move it is. Such games do not count in the statistics. Clicking the button again returns to a game against the computer."),
("Statystyki i ", "Statistics and settings"),
("liczba rozegr", "the number of games played and won and the win percentage, separately for each computer level and for network games."),
("aktualizacje,", "updates, game level, automatic moves, foundation obligation, volume and own sounds, keyboard shortcuts. The game remembers the group you selected last."),
("Cofanie i zap", "Undo and saving"),
("Cofnij cofa T", "Undo takes back your last action: a move, a draw, a discard, and moving a whole sequence as one step. If that action ended the turn, it also takes back the computer's moves made since then."),
("Stan gry zapi", "The state of the game is saved continuously and loaded at the next start (also after a crash)."),
("Komputer ma t", "The computer has three difficulty levels: Easy, Normal and Hard (change them in Settings). They differ only in how many moves ahead they look: 1, 2 and 4. The computer always plays what it judges the best series of moves, and does not end its turn when there is a free column that can take a card. It plays by the rules described in the file AI_RULES.md."),
("Dobierz kartę", "Draw a card from the stock"),
("Odrzuć kartę ", "Discard a card / pass"),
("Dźwięk włącz", "Sound on / off"),
("Ruch karty", "Card move"),
("Wygrana", "Win"),
("Przegrana lub", "Loss or draw"),
("Ruch niemożli", "Impossible move"),
("Cofnięcie ruc", "Undo of a move"),
("Przesunięcie ", "Flame moving"),
("Błąd serwera", "Server error."),
("Nieprawidłowe", "Wrong server password."),
("Nick: 3-16 zn", "Nickname: 3-16 characters, letters, digits, _ or -."),
("Błędny klucz ", "Invalid player key."),
("Serwer nie pr", "The server accepts no more new nicknames."),
("Ten nick jest", "This nickname is already taken by another player."),
("Najpierw zalo", "Log in first."),
("Brak wolnych ", "No free rooms, try again in a moment."),
("Nie ma takieg", "There is no such room."),
("Pokój jest ju", "The room is already full."),
]
