"""Builds res/lang/en.po: lists the Polish texts of the program (every T(L"...") in src/main.cpp, the label tables, the
rules text and the server's messages) and pairs them, in order, with the English texts of tools/en_list.py.
    python tools/i18n_build.py
Prints the texts that are out of step when a text was added to or removed from the code without the list."""
import re, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
G = os.path.join(HERE, '..') + '/'
sys.path.insert(0, HERE)
from en_list import EN

LIT = re.compile(r'L"((?:[^"\\]|\\.)*)"')

def dec(s):
    out = []
    i = 0
    while i < len(s):
        c = s[i]
        if c == '\\' and i + 1 < len(s):
            n = s[i + 1]
            i += 2
            out.append({'n': '\n', 't': '\t', '"': '"', '\\': '\\'}.get(n, n))
        else:
            out.append(c)
            i += 1
    return ''.join(out)

ids = []
def add(s):
    s = dec(s)
    if s not in ids:
        ids.append(s)

main = open(G + 'src/main.cpp', encoding='utf-8').read()
for m in re.finditer(r'T\(L"((?:[^"\\]|\\.)*)"\)', main):
    add(m.group(1))
for name in ['LEVEL_NAMES\\[\\]', 'SET_GROUPS\\[5\\]']:
    m = re.search(r'static const wchar_t\* ' + name + r'=\{(.*?)\};', main)
    for l in LIT.findall(m.group(1)):
        add(l)
m = re.search(r'HELP_DOC\[\]=\{(.*?)\n\};', main, re.S)
for line in m.group(1).split('\n'):
    for l in LIT.findall(line):
        add(l)
keys = open(G + 'src/keys.h', encoding='utf-8').read()
m = re.search(r'KA_LABELS\[KA_COUNT\]=\{(.*?)\};', keys, re.S)
for l in LIT.findall(m.group(1)):
    add(l)
snd = open(G + 'src/sound.h', encoding='utf-8').read()
m = re.search(r'SOUND_LABELS\[\] = \{(.*?)\};', snd, re.S)
for l in LIT.findall(m.group(1)):
    add(l)
srv = open(G + 'server/src/index.js', encoding='utf-8').read()
for m in re.finditer(r'this\.err\(ws, "[a-z]+", "([^"]+)"\)', srv):
    add(m.group(1))

if len(ids) != len(EN):
    print('count mismatch: %d texts in the code, %d in tools/en_list.py' % (len(ids), len(EN)))
bad = 0
for i, (pl, (pre, en)) in enumerate(zip(ids, EN)):
    if not pl.startswith(pre):
        print('out of step at %d: the code has %r, the list has %r' % (i, pl[:40], pre))
        bad += 1
        if bad > 4:
            break
if bad or len(ids) != len(EN):
    sys.exit(1)

def q(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\t', '\\t') + '"'

out = ['# English translation of Garibaldka. The source language of the program is Polish (msgid = the Polish text).',
       '# Generated by tools/i18n_build.py from tools/en_list.py. To add a language, put an xx.po file (same format) into the',
       '# "lang" folder next to the exe; its header gives the language: "Language: xx" and "Language-Name: ...".',
       'msgid ""', 'msgstr ""', '"Language: en\\n"', '"Language-Name: English\\n"', '"Content-Type: text/plain; charset=UTF-8\\n"', '']
for pl, (pre, en) in zip(ids, EN):
    if en is None:
        continue
    out += ['msgid ' + q(pl), 'msgstr ' + q(en), '']
open(G + 'res/lang/en.po', 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
print(len(ids), 'texts,', sum(1 for _, e in EN if e), 'translated -> res/lang/en.po')
